# Generated by Django 3.2.12 on 2022-02-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.AddIndex(
            model_name='userdetails',
            index=models.Index(fields=['user_name'], name='user_detail_user_na_df87f9_idx'),
        ),
    ]
