# Generated by Django 3.2.12 on 2022-02-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220216_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('ip_address', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_login_history',
            },
        ),
    ]
